import logging
import os

from dotenv import load_dotenv
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_openai import ChatOpenAI
from pydantic import BaseModel

import events
from memory import SessionMemory

load_dotenv()

API_KEY = os.environ.get("API_KEY", "")
BASE_URL = "https://legion1.di.uoa.gr/v1"
MODEL = "llama3.1"

llm = ChatOpenAI(
    model=MODEL,
    base_url=BASE_URL,
    api_key=API_KEY,
    max_completion_tokens=2048,
)

SYSTEM_PROMPT = (
    "You are Hyperion, an AI assistant designed to help deploy and manage applications "
    "across the Cloud-Edge-IoT computing continuum. You live inside the HyperAI IDE. "
    "Answer clearly and briefly."
)

log = logging.getLogger("hyperion")
memory = SessionMemory()

app = FastAPI(title="Hyperion Agent")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


class ChatRequest(BaseModel):
    user_id: str  # a UUID automatically generated by the IDE — use it to keep per-user session memory
    text: str  # the text the user typed in the chat


async def generate_reply(request: ChatRequest):
    messages = [
        SystemMessage(SYSTEM_PROMPT),
        *memory.history(request.user_id),
        HumanMessage(request.text),
    ]

    reply = ""
    try:
        async for chunk in llm.astream(messages):
            if chunk.text:
                reply += chunk.text
                yield events.text(chunk.text)
    except Exception:
        log.exception("LLM request failed")
        yield events.text("Sorry, I can't reach the language model right now. Please try again.")
    else:
        # Save completed turn
        memory.add_turn(request.user_id, request.text, reply)

    yield events.done()


@app.post("/chat")
async def chat(request: ChatRequest):
    return StreamingResponse(generate_reply(request), media_type="text/event-stream")


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8000)
